#!/bin/bash
IFS=$'\n'
bundle='bundle'
autoload='autoload'

plugins=(
    https://github.com/Raimondi/delimitMate.git
    https://github.com/jgdavey/vim-blockle.git
    https://github.com/kana/vim-textobj-entire.git
    https://github.com/kana/vim-textobj-lastpat.git
    https://github.com/kana/vim-textobj-line.git
    https://github.com/kana/vim-textobj-user.git
    https://github.com/kchmck/vim-coffee-script.git
    https://github.com/kien/ctrlp.vim.git
    https://github.com/lambdalisue/vim-django-support.git
    https://github.com/majutsushi/tagbar.git
    https://github.com/mattn/gist-vim.git
    https://github.com/mattn/webapi-vim.git
    https://github.com/mileszs/ack.vim.git
    https://github.com/msanders/snipmate.vim.git
    https://github.com/nelstrom/vim-textobj-rubyblock.git
    https://github.com/pangloss/vim-javascript.git
    https://github.com/scrooloose/nerdtree.git
    https://github.com/scrooloose/syntastic.git
    https://github.com/shawncplus/phpcomplete.vim.git
    https://github.com/sukima/xmledit.git
    https://github.com/szw/moloterm.git
    https://github.com/szw/rope-vim.git
    https://github.com/szw/vim-bufferlist.git
    https://github.com/szw/vim-dict.git
    https://github.com/szw/vim-g.git
    https://github.com/szw/vim-maximizer.git
    https://github.com/szw/vim-powerline.git
    https://github.com/szw/vim-smartclose.git
    https://github.com/szw/vim-tags.git
    https://github.com/szw/vim-testrunner.git
    https://github.com/terryma/vim-multiple-cursors.git
    https://github.com/tpope/vim-abolish.git
    https://github.com/tpope/vim-characterize.git
    https://github.com/tpope/vim-commentary.git
    https://github.com/tpope/vim-dispatch.git
    https://github.com/tpope/vim-endwise.git
    https://github.com/tpope/vim-fugitive.git
    https://github.com/tpope/vim-haml.git
    https://github.com/tpope/vim-markdown.git
    https://github.com/tpope/vim-rails.git
    https://github.com/tpope/vim-rake.git
    https://github.com/tpope/vim-repeat.git
    https://github.com/tpope/vim-surround.git
    https://github.com/tpope/vim-unimpaired.git
    https://github.com/vim-ruby/vim-ruby.git
    https://github.com/vim-scripts/Tabmerge.git
    https://github.com/vim-scripts/indentpython.vim.git
)

function get_pathogen {
    if [ ! -d "$autoload" ]; then
        mkdir $autoload
    fi
    cd $autoload
    curl -so pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
    cd ..
}

function do_xmledit_postinstall {
    if [ -d "$bundle/xmledit/ftplugin" ]; then
        cd $bundle/xmledit/ftplugin
        ln -s xml.vim eruby.vim 2>/dev/null
        ln -s xml.vim html.vim 2>/dev/null
        ln -s xml.vim xhtml.vim 2>/dev/null
        cd ../../..
    fi
}

function do_install {
    if [ ! -d "$bundle" ]; then
        mkdir $bundle
    fi
    cd $bundle
    for index in ${!plugins[*]}
    do
        git clone ${plugins[$index]} 2>/dev/null
    done
    cd ..

    do_xmledit_postinstall
}

function usage {
	echo "usage: $0 [update|install|help]"
}

function do_update {
	for dir in `ls "$bundle/"`
	do
		if [ -d "$bundle/$dir" ]; then
			cd $bundle/$dir
			git pull
			cd ../..
		fi
	done
}

echo 'PATHOSET v. 0.2'
echo 'Copyright (c) 2013 Szymon Wrozynski and Contributors'
echo
echo "Number of plugins: ${#plugins[*]}"
echo

if [ -z "$1" ]; then
    echo "Trying to install new plugins and update..."
    echo
    get_pathogen
    do_install
    do_update
elif [ "$1" = "update" ]; then
    echo "Trying to update..."
    echo
    get_pathogen
    do_update
elif [ "$1" = "install" ]; then
    echo "Trying to install new plugins..."
    echo
    get_pathogen
    do_install
else
	usage
fi

